language: java

jdk:
  - openjdk8
  - openjdk11
  - openjdk13
  - openjdk-ea

matrix:
  allow_failures:
    - jdk: openjdk-ea

dist: trusty

after_success:
  - mvn clean test jacoco:report coveralls:report
