language: java

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk8
  - openjdk11
  - openjdk15
  - openjdk-ea

matrix:
  allow_failures:
    - jdk: openjdk-ea

dist: trusty

after_success:
  - mvn clean test jacoco:report coveralls:report
